/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagementsystem;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class StudentModifyProfile extends javax.swing.JFrame {

    private String TP;
    private String PW;

    /**
     * Creates new form StudentModifyProfile
     */
    public StudentModifyProfile() {

        initComponents();
        // Additional initialization code if needed
    }

    public StudentModifyProfile(String TP, String PW) {

        String stdFirstName = "", stdLastName = "", stdDay = "", stdMonth = "", stdYear = "", stdDOB = "", stdGender = "", stdEmail = "", stdPhoneNo = "", stdAddress = "", stdIcNo = "", stdTpNo = "", stdPassword = "";
        //String[] vName = {stdFirstName, stdLastName, stdGender, stdDOB, stdEmail, stdPhoneNo, stdAddress, stdIcNo, stdTpNo, stdPassword};

        initComponents();
        this.TP = TP;
        this.PW = PW;

        String[] accountDetails = Student.retrieveData(TP, PW);
        stdFirstName = accountDetails[0];
        stdLastName = accountDetails[1];
        stdDOB = accountDetails[2];
        String[] dobParts = stdDOB.split("-");
        stdDay = dobParts[0];    // Day 
        stdMonth = dobParts[1];  // Month 
        stdYear = dobParts[2];   // Year 
        stdGender = accountDetails[3];
        stdEmail = accountDetails[4];
        stdPhoneNo = accountDetails[5];
        stdAddress = accountDetails[6];
        stdIcNo = accountDetails[7];
        stdTpNo = accountDetails[8];
        stdPassword = accountDetails[9];

        if (stdGender.equals("Male")) {
            genderMaleRBtn.setSelected(true);
        } else {
            genderFemaleRBtn.setSelected(true);
        }
        dobDayComboBox.setSelectedItem(stdDay);
        dobMonthComboBox.setSelectedItem(stdMonth);
        dobYearComboBox.setSelectedItem(stdYear);
        firstName_txt.setText(stdFirstName);
        lastName_txt.setText(stdLastName);
        eMail_txt.setText(stdEmail);
        phNo_txt.setText(stdPhoneNo);
        address_txt.setText(stdAddress);
        icNo_txt.setText(stdIcNo);
        tpNo_txt.setText(stdTpNo);
        password_txt.setText(stdPassword);
        cpassword_txt.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstName_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dobDayComboBox = new javax.swing.JComboBox<>();
        dobMonthComboBox = new javax.swing.JComboBox<>();
        dobYearComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lastName_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eMail_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genderFemaleRBtn = new javax.swing.JRadioButton();
        genderMaleRBtn = new javax.swing.JRadioButton();
        phNo_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        icNo_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        password_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cpassword_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        modify = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tpNo_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setPreferredSize(new java.awt.Dimension(1040, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("EDIT PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel2.setText("First Name");

        firstName_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        firstName_txt.setForeground(new java.awt.Color(102, 102, 102));
        firstName_txt.setText("Lim Lip How");
        firstName_txt.setToolTipText("");
        firstName_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        firstName_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        firstName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_txtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setText("Birthday");

        dobDayComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dobDayComboBox.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        dobDayComboBox.setForeground(new java.awt.Color(204, 204, 204));
        dobDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dobDayComboBox.setBorder(null);
        dobDayComboBox.setPreferredSize(new java.awt.Dimension(68, 28));

        dobMonthComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dobMonthComboBox.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        dobMonthComboBox.setForeground(new java.awt.Color(102, 102, 102));
        dobMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        dobMonthComboBox.setBorder(null);
        dobMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobMonthComboBoxActionPerformed(evt);
            }
        });

        dobYearComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dobYearComboBox.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        dobYearComboBox.setForeground(new java.awt.Color(102, 102, 102));
        dobYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        dobYearComboBox.setBorder(null);
        dobYearComboBox.setPreferredSize(new java.awt.Dimension(68, 28));
        dobYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobYearComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");

        lastName_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        lastName_txt.setForeground(new java.awt.Color(102, 102, 102));
        lastName_txt.setText("Lim Lip How");
        lastName_txt.setToolTipText("");
        lastName_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        lastName_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        lastName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_txtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        eMail_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        eMail_txt.setForeground(new java.awt.Color(102, 102, 102));
        eMail_txt.setText("Lim Lip How");
        eMail_txt.setToolTipText("");
        eMail_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        eMail_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        eMail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMail_txtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel7.setText("Gender");

        gender.add(genderFemaleRBtn);
        genderFemaleRBtn.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        genderFemaleRBtn.setForeground(new java.awt.Color(102, 102, 102));
        genderFemaleRBtn.setText("Female");
        genderFemaleRBtn.setBorder(null);

        gender.add(genderMaleRBtn);
        genderMaleRBtn.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        genderMaleRBtn.setForeground(new java.awt.Color(102, 102, 102));
        genderMaleRBtn.setText("Male");

        phNo_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        phNo_txt.setForeground(new java.awt.Color(102, 102, 102));
        phNo_txt.setText("Lim Lip How");
        phNo_txt.setToolTipText("");
        phNo_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        phNo_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        phNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phNo_txtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel8.setText("Phone Number");

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel9.setText("Address");

        address_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        address_txt.setForeground(new java.awt.Color(102, 102, 102));
        address_txt.setText("Lim Lip How");
        address_txt.setToolTipText("");
        address_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        address_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        icNo_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        icNo_txt.setForeground(new java.awt.Color(102, 102, 102));
        icNo_txt.setText("Lim Lip How");
        icNo_txt.setToolTipText("");
        icNo_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        icNo_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        icNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icNo_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel10.setText("IC Number");

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel11.setText("TP Number");

        password_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        password_txt.setForeground(new java.awt.Color(102, 102, 102));
        password_txt.setText("Lim Lip How");
        password_txt.setToolTipText("");
        password_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        password_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        password_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_txtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel12.setText("Password");

        cpassword_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        cpassword_txt.setForeground(new java.awt.Color(102, 102, 102));
        cpassword_txt.setText("Lim Lip How");
        cpassword_txt.setToolTipText("");
        cpassword_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        cpassword_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        cpassword_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassword_txtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel13.setText("Confirm Password");

        modify.setBackground(new java.awt.Color(236, 107, 38));
        modify.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        modify.setForeground(new java.awt.Color(255, 255, 255));
        modify.setText("Save Changes");
        modify.setBorder(null);
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        ClearAll.setBackground(new java.awt.Color(236, 107, 38));
        ClearAll.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        ClearAll.setForeground(new java.awt.Color(255, 255, 255));
        ClearAll.setText("Clear All");
        ClearAll.setBorder(null);
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(236, 107, 38));
        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tpNo_txt.setFont(new java.awt.Font("Segoe UI Variable", 3, 24)); // NOI18N
        tpNo_txt.setText("tpNo_txt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(firstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(genderMaleRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(genderFemaleRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(dobDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dobYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(eMail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(icNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(cpassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tpNo_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(dobMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eMail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dobYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genderMaleRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderFemaleRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(icNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tpNo_txt)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_txtActionPerformed

    private void lastName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_txtActionPerformed

    private void eMail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMail_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMail_txtActionPerformed

    private void phNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phNo_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void icNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icNo_txtActionPerformed

    private void password_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtActionPerformed

    private void cpassword_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassword_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassword_txtActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        String stdFirstName = firstName_txt.getText();
        String stdLastName = lastName_txt.getText();
        String stdGender = genderMaleRBtn.isSelected() ? "Male" : "Female";
        String stdDay = (String) dobDayComboBox.getSelectedItem();
        String stdMonth = (String) dobMonthComboBox.getSelectedItem();
        String stdYear = (String) dobYearComboBox.getSelectedItem();
        String stdDOB = stdDay + "-" + stdMonth + "-" + stdYear;
        String stdEmail = eMail_txt.getText();
        String stdPhoneNo = phNo_txt.getText();
        //String stdAddress = address_txt.getText();
        String stdAddress = address_txt.getText().replaceAll("\n", " ");
        String stdIcNo = icNo_txt.getText();
        String stdTpNo = tpNo_txt.getText();
        String stdPassword = password_txt.getText();
        String stdCpassword = cpassword_txt.getText();                    //Student.modifyProfile(TP, PW, firstName_txt, lastName_txt, newDOB, newGender, eMail_txt, phNo_txt, address_txt, icNo_txt, password_txt);
        boolean hasError = false;
        System.out.println(stdTpNo);
        String[] fields = {stdFirstName, stdLastName, stdDay, stdMonth, stdYear, stdEmail, stdPhoneNo, stdAddress, stdIcNo, stdTpNo, stdPassword, stdCpassword};
        for (String field : fields) {
            if (field == null || field.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all the credentials.", "Warning", JOptionPane.WARNING_MESSAGE);
                hasError = true;
                break;
            }
            if (field.contains("|")) {
                JOptionPane.showMessageDialog(null, "Illegal character '|' detected. Please remove this character and try again.", "Warning", JOptionPane.WARNING_MESSAGE);
                hasError = true;
                break;
            }
            if (field.equals(stdEmail)) {
                if (!stdEmail.contains("@")) {
                    JOptionPane.showMessageDialog(null, "Email should contain '@'. Please check and try again.", "Warning", JOptionPane.WARNING_MESSAGE);
                    hasError = true;
                    break;
                }
            }
            if (field.equals(stdPhoneNo)) {
                if (!stdPhoneNo.matches("[0-9-+]+")) {
                    JOptionPane.showMessageDialog(null, "Phone number should contain only numbers, '-' or '+'. Please check and try again.", "Warning", JOptionPane.WARNING_MESSAGE);
                    hasError = true;
                    break;
                }
            }
        }
        if (!hasError) {
            if (!stdPassword.equals(stdCpassword)) {
                JOptionPane.showMessageDialog(null, "Password does not match.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                Student newstd= new Student(TP,PW);
                if(newstd.modifyProfile(TP, PW, stdFirstName, stdLastName, stdDOB, stdGender, stdEmail, stdPhoneNo, stdAddress, stdIcNo, stdCpassword)){
                this.PW = stdCpassword;
                exithere();
                }
                
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
        firstName_txt.setText("");
        lastName_txt.setText("");
        dobDayComboBox.setSelectedItem(null);
        dobMonthComboBox.setSelectedItem(null);
        dobYearComboBox.setSelectedItem(null);
        eMail_txt.setText("");
        phNo_txt.setText("");
        address_txt.setText("");
        icNo_txt.setText("");
        tpNo_txt.setText("");
        password_txt.setText("");
        cpassword_txt.setText("");
        gender.clearSelection();          // TODO add your handling code here:
    }//GEN-LAST:event_ClearAllActionPerformed
    private void exithere() {
        System.out.println("thisis" + TP + PW);
        StudentHomePage StudentHomePageForm = new StudentHomePage(TP, PW);
        StudentHomePageForm.setVisible(true);
        this.dispose();

    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        exithere();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void dobMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobMonthComboBoxActionPerformed
        int selectedMonth = dobMonthComboBox.getSelectedIndex() + 1; // January is 1
        int selectedYear = Integer.parseInt((String) dobYearComboBox.getSelectedItem());
        int maxDays = 0;

        switch (selectedMonth) {
            case 2: // February
                if ((selectedYear % 4 == 0 && selectedYear % 100 != 0) || selectedYear % 400 == 0) {
                    maxDays = 29; // Leap year
                } else {
                    maxDays = 28; // Non-leap year
                }
                break;
            case 4: // April
            case 6: // June
            case 9: // September
            case 11: // November
                maxDays = 30; // 30 days
                break;
            default: // All other months
                maxDays = 31; // 31 days
                break;
        }

        // Update the day combo box model
        DefaultComboBoxModel<String> dayModel = (DefaultComboBoxModel<String>) dobDayComboBox.getModel();
        int selectedIndex = dobDayComboBox.getSelectedIndex();

        dayModel.removeAllElements();

        for (int i = 1; i <= maxDays; i++) {
            dayModel.addElement(String.valueOf(i));
        }

        if (selectedIndex >= maxDays) {
            dobDayComboBox.setSelectedIndex(maxDays - 1);
        } else {
            dobDayComboBox.setSelectedIndex(selectedIndex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dobMonthComboBoxActionPerformed

    private void dobYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobYearComboBoxActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentModifyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearAll;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField cpassword_txt;
    private javax.swing.JComboBox<String> dobDayComboBox;
    private javax.swing.JComboBox<String> dobMonthComboBox;
    private javax.swing.JComboBox<String> dobYearComboBox;
    private javax.swing.JTextField eMail_txt;
    private javax.swing.JTextField firstName_txt;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JRadioButton genderFemaleRBtn;
    private javax.swing.JRadioButton genderMaleRBtn;
    private javax.swing.JTextField icNo_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastName_txt;
    private javax.swing.JButton modify;
    private javax.swing.JTextField password_txt;
    private javax.swing.JTextField phNo_txt;
    private javax.swing.JLabel tpNo_txt;
    // End of variables declaration//GEN-END:variables
}
