/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagementsystem;


import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StudentBooking extends javax.swing.JFrame {

    String RoomNumber;
    String TP;
    String PW;
    double RoomPriceMonth = 1;
    double TotalRoomPrice;
    int RoomDuration = 1;
    String BookedYear;
    String BookedMonth;
    private static final DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form StudentBooking
     */
    public StudentBooking() {
        initComponents();
    }

    public StudentBooking(String RoomNumber, String TP, String PW) {
        this.RoomNumber = RoomNumber;
        this.TP = TP;
        this.PW = PW;
        initComponents();
        LoadRoomData();
        LoadCredential();
        DurationCB.setSelectedIndex(0);

    }

    private void LoadRoomData() {

        ArrayList<String> SelectedRoomsDetails = new ArrayList<>();
        SelectedRoomsDetails = room.RoomDetails(RoomNumber);
        for (String roomDetails : SelectedRoomsDetails) {
            String[] roomData = roomDetails.split("\\|");
            // Extracting only the required columns (Room Type, Room Number, and Price)
            RoomNoPO.setText(roomData[1]);
            RoomNo.setText(roomData[1]);
            RoomType.setText(roomData[0]);
            RoomPrice.setText(roomData[2]);
            RoomPricePO.setText(roomData[2]);
            RoomDesc.setText(roomData[3]);
            RoomPriceMonth = Double.parseDouble(roomData[2]);
        }

    }

    private void LoadCredential() {
        String[] accountDetails = Student.retrieveData(TP, PW);
        System.out.println(accountDetails);
        eMail_txt.setText(accountDetails[4]);
        phNo_txt.setText(accountDetails[5]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBGWhiteGrey = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BACKbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        firstName_txt1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        RoomNoPO = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RoomType = new javax.swing.JLabel();
        icNo_txt4 = new javax.swing.JLabel();
        RoomPrice = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eMail_txt = new javax.swing.JTextField();
        phNo_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        DurationCB = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        acNo_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        RoomNo = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        RoomNo3 = new javax.swing.JLabel();
        DurationPO = new javax.swing.JLabel();
        RoomPricePO = new javax.swing.JLabel();
        PricePO1 = new javax.swing.JLabel();
        DurationPO1 = new javax.swing.JLabel();
        icNo_txt5 = new javax.swing.JLabel();
        TotalRoomPricePO = new javax.swing.JLabel();
        PricePO2 = new javax.swing.JLabel();
        RoomPricePO1 = new javax.swing.JLabel();
        RoomDesc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 247, 247));

        jPanelBGWhiteGrey.setBackground(new java.awt.Color(247, 247, 247));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setText("ROOM BOOKING");

        BACKbtn.setBackground(new java.awt.Color(236, 107, 38));
        BACKbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        BACKbtn.setForeground(new java.awt.Color(255, 255, 255));
        BACKbtn.setText("BACK");
        BACKbtn.setBorder(null);
        BACKbtn.setMaximumSize(new java.awt.Dimension(90, 20));
        BACKbtn.setMinimumSize(new java.awt.Dimension(90, 20));
        BACKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BACKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addComponent(BACKbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("ASIA PACIFIC UNIVERSITY");

        firstName_txt1.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        firstName_txt1.setText("APU HOSTEL");

        jLabel14.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Information");

        jLabel18.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel18.setText("The APU HOSTEL is equipped with 24/7 security and access card control.");

        jLabel17.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel17.setText("APU HOSTEL is located within APU’s Campus in Technology Park Malaysia.");

        jLabel19.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel19.setText("Students staying in the APU HOSTEL will have access to campus facilities.");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Room Number");

        RoomNoPO.setBackground(new java.awt.Color(255, 255, 255));
        RoomNoPO.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        RoomNoPO.setForeground(new java.awt.Color(255, 255, 255));
        RoomNoPO.setText("A-01-01");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Room Type");

        RoomType.setBackground(new java.awt.Color(255, 255, 255));
        RoomType.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        RoomType.setForeground(new java.awt.Color(255, 255, 255));
        RoomType.setText("Standard");

        icNo_txt4.setBackground(new java.awt.Color(255, 255, 255));
        icNo_txt4.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        icNo_txt4.setForeground(new java.awt.Color(255, 255, 255));
        icNo_txt4.setText("RM");

        RoomPrice.setBackground(new java.awt.Color(255, 255, 255));
        RoomPrice.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        RoomPrice.setForeground(new java.awt.Color(255, 255, 255));
        RoomPrice.setText("900.00");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" / Month");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive - Asia Pacific University\\DG Y2\\Semester 1\\OODJ\\A FINAL ASSIGNMENT\\HostelManagementSystem\\src\\main\\java\\com\\mycompany\\hostelmanagementsystem\\APU HOSTEL.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        eMail_txt.setEditable(false);
        eMail_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        eMail_txt.setForeground(new java.awt.Color(102, 102, 102));
        eMail_txt.setText("Lim Lip How");
        eMail_txt.setToolTipText("");
        eMail_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        eMail_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        eMail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMail_txtActionPerformed(evt);
            }
        });

        phNo_txt.setEditable(false);
        phNo_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        phNo_txt.setForeground(new java.awt.Color(102, 102, 102));
        phNo_txt.setText("Lim Lip How");
        phNo_txt.setToolTipText("");
        phNo_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        phNo_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        phNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phNo_txtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel8.setText("Phone Number");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setText("Check In Month-Year");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setText("Duration (Month)");

        monthComboBox.setForeground(new java.awt.Color(102, 102, 102));
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yearComboBox.setForeground(new java.awt.Color(102, 102, 102));
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025" }));

        DurationCB.setForeground(new java.awt.Color(102, 102, 102));
        DurationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        DurationCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationCBActionPerformed(evt);
            }
        });

        jComboBox4.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maybank (Malayan Banking Berhad)", "CIMB Bank (CIMB Group Holdings Berhad)", "Public Bank Berhad", "RHB Bank Berhad", "Hong Leong Bank Berhad", "AmBank (AmBank Group)", "Alliance Bank Malaysia Berhad", "OCBC Bank (Malaysia) Berhad", "UOB Malaysia (United Overseas Bank Malaysia)", "HSBC Bank Malaysia Berhad", "Standard Chartered Bank Malaysia Berhad", "Citibank Malaysia", "Affin Bank Berhad", "Bank Islam Malaysia Berhad", "Bank Muamalat Malaysia Berhad" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel7.setText("Bank");

        acNo_txt.setFont(new java.awt.Font("Segoe UI Historic", 2, 13)); // NOI18N
        acNo_txt.setForeground(new java.awt.Color(102, 102, 102));
        acNo_txt.setToolTipText("");
        acNo_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        acNo_txt.setSelectionColor(new java.awt.Color(153, 0, 0));
        acNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acNo_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel9.setText("Account Number");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Room Number");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total");

        RoomNo.setBackground(new java.awt.Color(255, 255, 255));
        RoomNo.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        RoomNo.setForeground(new java.awt.Color(255, 255, 255));
        RoomNo.setText("A-01-01");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Duration");

        RoomNo3.setBackground(new java.awt.Color(255, 255, 255));
        RoomNo3.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        RoomNo3.setForeground(new java.awt.Color(255, 255, 255));
        RoomNo3.setText("............................................................................................................................................................");

        DurationPO.setBackground(new java.awt.Color(255, 255, 255));
        DurationPO.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        DurationPO.setForeground(new java.awt.Color(255, 255, 255));

        RoomPricePO.setBackground(new java.awt.Color(255, 255, 255));
        RoomPricePO.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        RoomPricePO.setForeground(new java.awt.Color(255, 255, 255));
        RoomPricePO.setText("A-01-01");

        PricePO1.setBackground(new java.awt.Color(255, 255, 255));
        PricePO1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        PricePO1.setForeground(new java.awt.Color(255, 255, 255));
        PricePO1.setText("x");

        DurationPO1.setBackground(new java.awt.Color(255, 255, 255));
        DurationPO1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        DurationPO1.setForeground(new java.awt.Color(255, 255, 255));

        icNo_txt5.setBackground(new java.awt.Color(255, 255, 255));
        icNo_txt5.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        icNo_txt5.setForeground(new java.awt.Color(255, 255, 255));
        icNo_txt5.setText("RM");

        TotalRoomPricePO.setBackground(new java.awt.Color(255, 255, 255));
        TotalRoomPricePO.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        TotalRoomPricePO.setForeground(new java.awt.Color(255, 255, 255));
        TotalRoomPricePO.setText("0");

        PricePO2.setBackground(new java.awt.Color(255, 255, 255));
        PricePO2.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        PricePO2.setForeground(new java.awt.Color(255, 255, 255));
        PricePO2.setText("x");

        RoomPricePO1.setBackground(new java.awt.Color(255, 255, 255));
        RoomPricePO1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        RoomPricePO1.setForeground(new java.awt.Color(255, 255, 255));
        RoomPricePO1.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomType)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(icNo_txt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(eMail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(DurationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(acNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(RoomPricePO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(PricePO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RoomPricePO1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(PricePO2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(RoomNoPO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DurationPO1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DurationPO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(icNo_txt5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                                .addComponent(TotalRoomPricePO)))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoomType)
                            .addComponent(RoomNo))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eMail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DurationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoomNo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomPricePO1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(RoomNoPO, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PricePO2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(DurationPO, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(RoomPricePO, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PricePO1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DurationPO1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icNo_txt5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TotalRoomPricePO)
                                .addComponent(RoomPrice)
                                .addComponent(icNo_txt4)
                                .addComponent(jLabel26)))
                        .addGap(8, 8, 8))))
        );

        RoomDesc.setBackground(new java.awt.Color(255, 255, 255));
        RoomDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        RoomDesc.setText("Enjoy a peaceful and relaxing stay in this well-appointed standard room");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel25.setText("Room Details");

        jButton3.setBackground(new java.awt.Color(236, 107, 38));
        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MODIFY");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(90, 20));
        jButton3.setMinimumSize(new java.awt.Dimension(90, 20));

        submit.setBackground(new java.awt.Color(255, 102, 0));
        submit.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit Application");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGWhiteGreyLayout = new javax.swing.GroupLayout(jPanelBGWhiteGrey);
        jPanelBGWhiteGrey.setLayout(jPanelBGWhiteGreyLayout);
        jPanelBGWhiteGreyLayout.setHorizontalGroup(
            jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGWhiteGreyLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(15, 15, 15))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelBGWhiteGreyLayout.setVerticalGroup(
            jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName_txt1)
                    .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoomDesc))
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanelBGWhiteGreyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBGWhiteGreyLayout.createSequentialGroup()
                    .addGap(0, 356, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 357, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGWhiteGrey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGWhiteGrey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKbtnActionPerformed
        exithere();        // TODO add your handling code here:
    }//GEN-LAST:event_BACKbtnActionPerformed

    private void eMail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMail_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMail_txtActionPerformed

    private void phNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phNo_txtActionPerformed

    private void acNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acNo_txtActionPerformed

    private void DurationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationCBActionPerformed
        //String selectedDuration = (String) DurationCB.getSelectedItem();
        DurationPO.setText((String) DurationCB.getSelectedItem());
        DurationPO1.setText((String) DurationCB.getSelectedItem());
        String selectedDuration = (String) DurationCB.getSelectedItem();
        RoomDuration = Integer.parseInt(selectedDuration);
        TotalRoomPrice = RoomDuration * RoomPriceMonth;
        df.format(TotalRoomPrice);
        TotalRoomPricePO.setText(String.valueOf(df.format(TotalRoomPrice)));

    }//GEN-LAST:event_DurationCBActionPerformed

    private void exithere() {
        System.out.println("thisis" + TP + PW);
        StudentHomePage StudentHomePageForm = new StudentHomePage(TP, PW);
        StudentHomePageForm.setVisible(true);
        this.dispose();

    }


    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (acNo_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter account number");
        } else if (acNo_txt.getText().contains("|")) {
            JOptionPane.showMessageDialog(this, "Account number cannot contain the character '|'");
        } else {
            if (application.checkOngoingApplication(TP)) {
                JOptionPane.showMessageDialog(null, "Dear User: \n\n          "
                        + "You have PENDING or ACTIVE room aplication.    \n\n Please Try Again.", "Room Reserved", JOptionPane.WARNING_MESSAGE);
            } else {
                BookedYear = yearComboBox.getSelectedItem().toString();
                BookedMonth = monthComboBox.getSelectedItem().toString();
                String CheckIn = BookedMonth + "-" + BookedYear;
                String selectedDuration = DurationCB.getSelectedItem().toString();

                // Convert BookedYear, BookedMonth, and selectedDuration to integers
                int year = Integer.parseInt(BookedYear);
                int month = Integer.parseInt(BookedMonth);
                int RoomDuration = Integer.parseInt(selectedDuration);

                // Calculate the CheckOut year and month
                int checkOutYear = year + ((month + RoomDuration - 1) / 12);
                int checkOutMonth = (month + RoomDuration - 1) % 12 + 1;

                Random random = new Random();
                int randomNumber = random.nextInt(90000000) + 10000000;
                String refNo = String.valueOf(randomNumber);
                System.out.println(refNo);

                // Format the CheckOut date string
                String CheckOut = checkOutMonth + "-" + checkOutYear;
                System.out.println(TP + "|" + RoomNumber + "|" + CheckIn + "|" + CheckOut + "|" + RoomDuration + "|" 
                        + df.format(TotalRoomPrice) + "|" + "Pending" + "|" + refNo + "\n");
                String dataSubmit = (TP + "|" + RoomNumber + "|" + CheckIn + "|" + CheckOut + "|" + RoomDuration + "|" 
                        + df.format(TotalRoomPrice) + "|" + "Pending" + "|" + refNo + "\n");
                application.addApplication(dataSubmit);
                System.out.println(RoomNumber);
                roomStatus.modifyRoomStatus(RoomNumber, refNo,"Unavailable");
                exithere();
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.out.println("ouch");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKbtn;
    private javax.swing.JComboBox<String> DurationCB;
    private javax.swing.JLabel DurationPO;
    private javax.swing.JLabel DurationPO1;
    private javax.swing.JLabel PricePO1;
    private javax.swing.JLabel PricePO2;
    private javax.swing.JLabel RoomDesc;
    private javax.swing.JLabel RoomNo;
    private javax.swing.JLabel RoomNo3;
    private javax.swing.JLabel RoomNoPO;
    private javax.swing.JLabel RoomPrice;
    private javax.swing.JLabel RoomPricePO;
    private javax.swing.JLabel RoomPricePO1;
    private javax.swing.JLabel RoomType;
    private javax.swing.JLabel TotalRoomPricePO;
    private javax.swing.JTextField acNo_txt;
    private javax.swing.JTextField eMail_txt;
    private javax.swing.JLabel firstName_txt1;
    private javax.swing.JLabel icNo_txt4;
    private javax.swing.JLabel icNo_txt5;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelBGWhiteGrey;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JTextField phNo_txt;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
